<?php

namespace GFExcel\Tests\Repository;

use GFExcel\Repository\FormRepository;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class FormRepositoryTest extends TestCase
{
    /**
     * The class under test.
     * @since $ver$
     * @var FormRepository
     */
    private $repository;

    /**
     * Mocked GFAPI instance.
     * @since $ver$
     * @var \GFAPI|MockObject
     */
    private $api;

    /**
     * {@inheritdoc}
     * @since $ver$
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->api = $this->getMockBuilder(\stdClass::class)
            ->setMockClassName('GFAPI')
            ->addMethods(['get_entries'])
            ->getMock();

        $this->repository = new FormRepository($this->api);
    }

    /**
     * Test case for {@see FormRepository::getEntries}.
     * @since $ver$
     */
    public function testGetEntries()
    {
        $this->api
            ->expects($this->once())
            ->method('get_entries')
            ->with(1, ['active' => true], ['field' => 'ASC'])
            ->willReturn([['result']]);

        $result = $this->repository->getEntries(1, ['active' => true], ['field' => 'ASC']);
        $this->assertInstanceOf(\Generator::class, $result);
        foreach ($result as $value) {
            $this->assertEquals(['result'], $value);
        }
    }
}
